print("This is 3*3 matrix solver...")
r1c1 = input("Enter the number in the first row and first column: ")
r1c1n = int(r1c1)
r2c1 = input("Enter the number in the second row and first column: ")
r2c1n = int(r2c1)
r3c1 = input("Enter the number in the third row and first column: ")
r3c1n = int(r3c1)
r1c2 = input("Enter the number in the first row and second column: ")
r1c2n = int(r1c2)
r2c2 = input("Enter the number in the second row and second column: ")
r2c2n = int(r2c2)
r3c2 = input("Enter the number in the third row and second column: ")
r3c2n = int(r3c2)
r1c3 = input("Enter the number in the first row and third column: ")
r1c3n = int(r1c3)
r2c3 = input("Enter the number in the second row and third column: ")
r2c3n = int(r2c3)
r3c3 = input("Enter the number in the third row and third column: ")
r3c3n = int(r3c3)
det = r1c1n*(r2c2n*r3c3n - r3c2n*r2c3n) - r2c1n*(r1c2n*r3c3n - r3c2n*r1c3n) + r3c1n*(r1c2n*r2c3n - r2c2n*r1c3n)
print(det)
